version: "2"

services:
  preprocess:
    image: documentcloud/sidekick_preprocess
    build:
      context: ./preprocess
      dockerfile: ./Dockerfile
    environment:
      - collection
      - language
    volumes:
      - ./data:/code/data

  frontend_build:
    image: node:20.13.0
    volumes:
      - ./frontend:/app
    working_dir: /app
    command: npm i
